### PR TITLE
Added curved solar panels and RTGs as valid energy sources

### PR DESCRIPTION
**Pull request by PhilM-47**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
I need you to explain the 2nd commit, why are you removing the FuelCell?

**Comment by PhilM-47** [comment]
I originally added four new modules (RTG, curved solar panels, fuel cell, and fuel cell array), but then discovered that it doesn't work for the fuel cells, so I took the invalid lines back out before submitting the PR. Apparently fuel cells work as a resource converter and don't have an actual module named FuelCell which means the code that parses for energy sources didn't find them as I'd declared them. It will probably take some additional code to register fuel cells correctly, but I haven't looked too closely yet as I don't know C#.

**Comment by linuxgurugamer** [comment]
Ok.  What mods are the fuel cells in, I'll take a look.  In the meantime, I'll accept this, thanks

**Comment by PhilM-47** [comment]
They're just the default fuel cells and fuel cell arrays from squad. This is what they look like in my game. Obviously some of my mods have added their own tags to them, but I don't think any of them have changed their behavior significantly though. (The FuelCellArray is very similar)

UrlConfig
{
	name = FuelCell
	type = PART
	parentUrl = Squad/Parts/Resources/FuelCell/FuelCell
	url = Squad/Parts/Resources/FuelCell/FuelCell/FuelCell
	PART
	{
		name = FuelCell
		module = Part
		author = RoverDude
		rescaleFactor = 1
		node_attach = 0, 0, 0, 1, 0, 0, 0
		TechRequired = largeElectrics
		entryCost = 2250
		cost = 750
		category = Electrical
		subcategory = 0
		title = Fuel Cell
		manufacturer = Zaltonic Electronics
		description = A small fuel cell that allows fuel and oxidizer to be converted into energy.  Handy for those places where a solar panel will not do.  Also handy for re-heating snacks. New, improved model now has status light!
		attachRules = 0,1,0,0,0
		mass = 0.05
		dragModelType = default
		maximum_drag = 0.2
		minimum_drag = 0.2
		angularDrag = 2
		crashTolerance = 7
		maxTemp = 2000
		bulkheadProfiles = srf
		tags = array bank charge convert e/c elect energ pack power volt watt
		MODEL
		{
			model = Squad/Parts/Resources/FuelCell/FuelCell
		}
		MODULE
		{
			name = ModuleResourceConverter
			ConverterName = Fuel Cell
			StartActionName = Start Fuel Cell
			StopActionName = Stop Fuel Cell
			ToggleActionName = Toggle Fuel Cell
			FillAmount = 0.95
			AutoShutdown = false
			GeneratesHeat = false
			UseSpecialistBonus = false
			INPUT_RESOURCE
			{
				ResourceName = LiquidFuel
				Ratio = 0.0016875
				FlowMode = STAGE_PRIORITY_FLOW
			}
			INPUT_RESOURCE
			{
				ResourceName = Oxidizer
				Ratio = 0.0020625
				FlowMode = STAGE_PRIORITY_FLOW
			}
			OUTPUT_RESOURCE
			{
				ResourceName = ElectricCharge
				Ratio = 1.5
				DumpExcess = false
			}
		}
		RESOURCE
		{
			name = ElectricCharge
			amount = 50
			maxAmount = 50
		}
		MODULE
		{
			name = ModuleAGX
		}
		MODEL
		{
			model = IndicatorLights/Parts/fuelCells/rectangularIndicatorModel
			scale = 0.11077, 0.8, 0.5
			position = -0.19, 0, -0.07
			rotation = 0, 180, 0
		}
		MODULE
		{
			name = ModuleControllableEmissive
			target = IndicatorLights/Parts/fuelCells/rectangularIndicatorModel
			emissiveName = indicator
		}
		MODULE
		{
			name = ModuleConverterIndicator
			converterName = Fuel Cell
			emissiveName = indicator
		}
		MODULE
		{
			name = TweakScale
			type = free
		}
		MODULE
		{
			name = USI_ModuleRecycleablePart
			Menu = Disassemble Part
			ResourceName = MaterialKits
			Efficiency = .5
		}
		MODULE
		{
			name = SectionInfo
		}
		MODULE
		{
			name = SmartRename
		}
	}
}

**Comment by linuxgurugamer** [comment]
I found the fuel cell a while after I posted. 
I'll add this to my todo list,but it's going to be after 1.3 drops

**Comment by linuxgurugamer** [comment]
Would you be able to test something?
I've added the code necessary for the FuelCell and FuelCellArray.  Actually, I added code which, if there was a resource specified along with the name, look for the module and then look to see that it has the specified OUTPUT_RESOURCE, so now a single entry for ModuleResourceConverter should take care of both.
If you can, here is a link to the test version: 
https://www.dropbox.com/s/r3rlr556sk00jr6/stateFundingBeta.zip?dl=0

Please let me know, I don't have a lot of time right now to test.  If you can, also make sure that the normal energy sources also work.

**Comment by PhilM-47** [comment]
I tried out the new build and had good success with the changes, including the fuel cells. I tested some mod-added fuel cells as well (Octosat, Universal Storage) and those worked as expected. I did come across one quirk with a fuel cell added by USI (the DERP fuel cell). I think it's because it has its own ModuleResourceConverter which means it needs the lines below to recognize it.

Item		
 {		
 	name = ModuleResourceConverter_USI
	resource = ElectricCharge
 }

**Comment by linuxgurugamer** [comment]
Great, thanks.
I'll try to get a release out this evening

**Pull request merged**
